### ISSUE TITLE
Works offline but not online

### ISSUE THREAD

**Issue by SWDP** [JosHuybrighs/service.rmlmenu.jquery#2]
Hi there!
I'm using this plugin and it works perfectly fine offline but as soon as I upload it to any host it just doesn't work. I tried a lot of things but nothing works!
It's not a browser issue nor host issue.
As you can see in the image offline it works like a charm, but in the link below you can see what it became online:

http://sonountest.altervista.org/inizio.html

Clicking the word "menu" in the top left corner just opens a list with the buttons.

Help!

![problema sito franco menu](https://cloud.githubusercontent.com/assets/5917853/5944096/a032f814-a724-11e4-938f-a7c829ee382a.png)

**Comment by JosHuybrighs** [comment]
I will have a look at it tomorrow

**Comment by SWDP** [comment]
Oh, awesome! Fast reply, thanks a lot my friend!

2015-01-28 20:46 GMT+01:00 JosHuybrighs notifications@github.com:

> I will have a look at it tomorrow
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JosHuybrighs/service.rmlmenu.jquery/issues/2#issuecomment-71902092
> .

## 

_Sohl Weber_

**Comment by JosHuybrighs** [comment]
According to the Google Chrome inspector your server returns a 404 (Not Found) error for the following stylesheet and picture files:
 GET http://sonountest.altervista.org/content/Project/Css/site.css 
 GET http://sonountest.altervista.org/content/Project/Css/responsive.css 
 GET http://sonountest.altervista.org/content/Project/Css/tutorial.css 
 GET http://sonountest.altervista.org/css/service.rmlmenu.jquery.css 
 GET http://sonountest.altervista.org/content/Libs/service.rmlmenu.jquery-1.0.0/service.rmlmenu.jquery.css 
 GET http://sonountest.altervista.org/content/Project/Css/markdown.css 
 GET http://sonountest.altervista.org/ff.png

The only reason I can think of is that you either placed them somewhere else or that access to the files is forbidden  (Some servers return a 404 when access to a file is forbidden).
By the way it seems that you also have 2 'Content' folders: one with lowercase c, the other with uppercase C. That might lead to some confusion about where the files have actually been uploaded.

**Comment by SWDP** [comment]
Hey there! Gosh I have to thank you. In the end it was exactly the case
problem.
It was a combination of different case in capital letters both in the html
files and folders.
I still get the problem in one or two pages but I'm working on it.
Thank you so much! Really fast answers and hey, I asked my host and their
only reply was "it's nothing related to our services, we're sorry about
it", and you who gets nothing for it helped me, thank you!
Much appreciated, best regards!
Sohl Weber

2015-01-29 12:57 GMT+01:00 JosHuybrighs notifications@github.com:

> According to the Google Chrome inspector your server returns a 404 (Not
> Found) error for the following stylesheet and picture files:
> GET http://sonountest.altervista.org/content/Project/Css/site.css
> GET http://sonountest.altervista.org/content/Project/Css/responsive.css
> GET http://sonountest.altervista.org/content/Project/Css/tutorial.css
> GET http://sonountest.altervista.org/css/service.rmlmenu.jquery.css
> GET
> http://sonountest.altervista.org/content/Libs/service.rmlmenu.jquery-1.0.0/service.rmlmenu.jquery.css
> GET http://sonountest.altervista.org/content/Project/Css/markdown.css
> GET http://sonountest.altervista.org/ff.png
> 
> The only reason I can think of is that you either placed them somewhere
> else or that access to the files is forbidden (Some servers return a 404
> when access to a file is forbidden).
> By the way it seems that you also have 2 'Content' folders: one with
> lowercase c, the other with uppercase C. That might lead to some confusion
> about where the files have actually been uploaded.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JosHuybrighs/service.rmlmenu.jquery/issues/2#issuecomment-72012948
> .

## 

_Sohl Weber_

**Comment by ThomasHutchinson** [comment]
A silly question is one not asked!. If the problem was to do with this framework he would of received valuable feedback and the value of his platform as a hole would of increased. I also looked at your page and you should use code injection for the headers and any code shared between all pages, that way a change is instant across every page.

**Comment by SWDP** [comment]
Hi again and of course thanks again! ahah

You're awesome, whoever you are, and it really is a pleasure to have met you
in this f**kin large Internet.

I'm into web design from some time ago, a bit for the liking and a bit for
necessity but you know, every little bite of information help getting the
work done properly and this was one of those cases.

Aaaand I think I'll try to borrow some other pearls from your pot of
knowledge. Ahah
So please, answer only if you have the time and desire to. Even links to
tutorials or pages where I can find information for my troubles would be
fantastic!

It's all related to the website I'm making to an artist friend. http://www.
francotomatis.it
1. I now get another error with the menu when it shrinks. When in resized
   window state the buttons all work perfectly but clicking them only open the sub
   menus and it doesn't redirects to the page linked to the said button. I
   tried a lot of thinks but can't figure it out, it's probably another simple
   matter. Duh
2. From the moment I implemented the menu in the website I get this black
   artifacts (rectangles) that appears here and there while scrolling up or
   down. What could it be? Is it normal? I also noticed it in other websites. I
   believe it has to do with the javascript in general but as of problem number
   1 I can't figure it out.
3. The third one has nothing to do with the menu.
   If you go to http://www.francotomatis.it/martyn.html you will see that
   there's a "book" in there. The book is supposed to be responsive but when
   the window resizes it will do shrink but also be "eaten" by the edges of the
   page and no scrolling bar appears, so I'm not able to see the eaten parts.
   Could it be related to the div structure I'm using?

Of course thanks a million times again and please don't diverge from your
business for me, It's a slow work anyways with this website. Ahah

As always my bestest regards to you and your work!

Sohl Weber

2015-01-30 0:06 GMT+01:00 ThomasHutchinson notifications@github.com:

> A silly question is one not asked!. If the problem was to do with this
> framework he would of received valuable feedback and the value of his
> platform as a hole would of increased. I also looked at your page and you
> should use code injection for the headers and any code shared between all
> pages, that way a change is instant across every page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JosHuybrighs/service.rmlmenu.jquery/issues/2#issuecomment-72122855
> .

## 

_Sohl Weber_

**Comment by JosHuybrighs** [comment]
Sohl,

####question 1
The fault here is that you apparantly are not initializing the plugin correctly. You are using:

```javascript
$(function () {
  $('#navMenu').rmlmenu({
    // Menu options here:
    pMenuBttn: '#popupMenuBttn',
    pMenuBackText: 'INDIETRO',
    onLinkClick: function (el, ev) {
      var anchor = $(el).find('a:first');
      $('#prompt').html("Clicked/touched: " + anchor.text());
      return true;
    }
  });
});
```
You probably took this from the demo page but that is a special page where the example menu shouldn't call other pages (simply because there aren't any).
The code must be:

```javascript
$(function () {
  $('#navMenu').rmlmenu({
    // Menu options here:
    pMenuBttn: '#popupMenuBttn',
    pMenuBackText: 'INDIETRO'
  });
});
```
The onLinkClick callback is only there for special purposes (as explained in the tutorial).

####question 2
I don't see any black artifacts when using Google Chrome or Internet Explorer. The liitle bit of Italian I understa The fault here is that you apparantly are not initializing the plugin correctly. You are using:

**Comment by SWDP** [comment]
And again. You saved me again, just like before simply changing that part
of code got rid of the black artifacts and made the button's links work
again even in resized state.
It seems I really can't get to solve those simple problems. Man, I solved
so many complicated issues with other websites and this one had only this
little pieces of crap that stole so many time from me.
Thanks, thanks a lot. I'm currently getting work done with the "eater"
window from the books page, it's probably another code issue. Haha
Thanks my savior!
Sohl Weber

2015-02-02 15:19 GMT+01:00 JosHuybrighs notifications@github.com:

> Sohl,
> 
> ####question 1
> The fault here is that you apparantly are not initializing the plugin
> correctly. You are using:
> 
> $(function () {
>   $('#navMenu').rmlmenu({
>     // Menu options here:
>     pMenuBttn: '#popupMenuBttn',
>     pMenuBackText: 'INDIETRO',
>     onLinkClick: function (el, ev) {
>       var anchor = $(el).find('a:first');
>       $('#prompt').html("Clicked/touched: " + anchor.text());
>       return true;
>     }
>   });
> });
> 
> You probably took this from the demo page but that is a special page where
> the example menu shouldn't call other pages (simply because there aren't
> any).
> The code must be:
> 
> $(function () {
>   $('#navMenu').rmlmenu({
>     // Menu options here:
>     pMenuBttn: '#popupMenuBttn',
>     pMenuBackText: 'INDIETRO'
>   });
> });
> 
> The onLinkClick callback is only there for special purposes (as explained
> in the tutorial).
> 
> ####question 2
> I don't see any black artifacts when using Google Chrome or Internet
> Explorer. The liitle bit of Italian I understa The fault here is that you
> apparantly are not initializing the plugin correctly. You are using:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JosHuybrighs/service.rmlmenu.jquery/issues/2#issuecomment-72464340
> .

## 

_Sohl Weber_

**Comment by JosHuybrighs** [comment]
No problem, always happy to help someone.

If you would be interested in using my 'responsive' grid framework, it is now available both on my webpage and on GitHub. See [code.cwwonline.be](http://code.cwwonline.be/responsivegrid).

I would anyhow encourage you to look into these concepts (mine or any other like foundation, ..) because it will otherwise be difficult to have the content correctly displayed on todays devices: smartphones, tablets of various sizes, laptops, etc.

Regards,
Jos
